name: Build and Release APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.1
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Setup Gradle Wrapper (if missing)
      run: |
        cd android
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "Gradle wrapper missing, creating it..."
          gradle wrapper --gradle-version 8.1.1
        fi
        chmod +x gradlew
        
    - name: Verify Gradle Setup
      run: |
        cd android
        ./gradlew --version
        
    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace
        
    - name: Build Release APK
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace
        
    - name: Get version info
      id: version
      run: |
        cd android
        VERSION_NAME=$(./gradlew -q printVersionName 2>/dev/null || echo "1.0.0")
        VERSION_CODE=$(./gradlew -q printVersionCode 2>/dev/null || echo "1")
        echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
        echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
        echo "build_time=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
        
    - name: Rename APK files
      run: |
        cd android/app/build/outputs/apk
        if [ -f "debug/app-debug.apk" ]; then
          mv debug/app-debug.apk debug/SpeedDrawer-debug-${{ steps.version.outputs.build_time }}.apk
        fi
        if [ -f "release/app-release.apk" ]; then
          mv release/app-release.apk release/SpeedDrawer-release-${{ steps.version.outputs.build_time }}.apk
        fi
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: SpeedDrawer-Debug-APK
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: SpeedDrawer-Release-APK
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 90
        
    - name: Get APK info
      id: apk_info
      run: |
        cd android/app/build/outputs/apk
        if [ -f debug/*.apk ]; then
          DEBUG_SIZE=$(du -h debug/*.apk | cut -f1)
          echo "debug_size=$DEBUG_SIZE" >> $GITHUB_OUTPUT
        else
          echo "debug_size=N/A" >> $GITHUB_OUTPUT
        fi
        if [ -f release/*.apk ]; then
          RELEASE_SIZE=$(du -h release/*.apk | cut -f1)
          echo "release_size=$RELEASE_SIZE" >> $GITHUB_OUTPUT
        else
          echo "release_size=N/A" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          android/app/build/outputs/apk/release/*.apk
        body: |
          # Speed Drawer v${{ steps.version.outputs.version_name }}
          
          ## 🚀 What's New
          - High-performance Kotlin Android launcher
          - Under 10MB APK size (${{ steps.apk_info.outputs.release_size }})
          - Instant app search with fuzzy matching
          - Material Design 3 UI
          - Dark/Light theme support
          - Favorite apps and usage tracking
          
          ## 📱 Installation
          1. Download the APK below
          2. Enable "Install from Unknown Sources" in Android settings
          3. Install the APK
          4. Set as default launcher (optional)
          
          ## 📊 Build Info
          - **Version**: ${{ steps.version.outputs.version_name }}
          - **Build**: ${{ steps.version.outputs.version_code }}
          - **APK Size**: ${{ steps.apk_info.outputs.release_size }}
          - **Build Time**: ${{ steps.version.outputs.build_time }}
          - **Min Android**: 6.0 (API 23)
          - **Target Android**: 14 (API 34)
          
          ## 🔒 Permissions
          - `QUERY_ALL_PACKAGES`: To list installed applications
          - `VIBRATE`: For haptic feedback (optional)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    # Create automatic release for main branch pushes (without tag)
    - name: Create Auto Release (on main push)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto-v${{ steps.version.outputs.version_name }}-${{ steps.version.outputs.build_time }}
        name: Auto Release v${{ steps.version.outputs.version_name }}-${{ steps.version.outputs.build_time }}
        files: |
          android/app/build/outputs/apk/release/*.apk
        body: |
          # 🤖 Automatic Release - Speed Drawer v${{ steps.version.outputs.version_name }}
          
          This is an automatically generated release from the latest main branch commit.
          
          ## 📱 Download APK
          - **Size**: ${{ steps.apk_info.outputs.release_size }}
          - **Build Time**: ${{ steps.version.outputs.build_time }}
          - **Commit**: ${{ github.sha }}
          
          ## 🚀 Features
          - Native Kotlin Android launcher
          - Material Design 3 UI  
          - Fuzzy search functionality
          - Favorites and usage tracking
          - Dark/Light theme support
          
          ## 📱 Installation
          1. Download the APK below
          2. Enable "Install from Unknown Sources" in Android settings
          3. Install the APK
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.1
        
    - name: Setup Gradle Wrapper (if missing)
      run: |
        cd android
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          gradle wrapper --gradle-version 8.1.1
        fi
        chmod +x gradlew
        
    - name: Run Unit Tests
      run: |
        cd android
        ./gradlew test --stacktrace || true
        
    - name: Run Lint Check
      run: |
        cd android
        ./gradlew lint --stacktrace || true
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: android/app/build/test-results/
        retention-days: 30
        
    - name: Upload Lint Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: android/app/build/reports/
        retention-days: 30 